import bcrypt from 'bcryptjs';
const data = {

  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
    products: [
        {
            name: 'Iphone 13',
            category: 'Phone',
            image: '/images/iphone13.jpg',
            price: 800,
            brand: 'Apple',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            isFeatured: true,
            featuredImage: '/images/Techzone.png',
            slug:'iphone13',
            description: 'A popular mobile phone',
          },
      {
        name: 'Iphone 13 Pro',
        category: 'Phone',
        image: '/images/iphone13.jpg',
        price: 1200,
        brand: 'Apple',
        rating: 4.5,
        numReviews: 10,
        slug:'iphone13Pro',
        countInStock: 20,
        description: 'A popular mobile phone',
      },
      {
        name: 'Iphone 13 Pro Max',
        category: 'Phone',
        image: '/images/iphone13.jpg',
        price: 1300,
        brand: 'Apple',
        rating: 4.5,
        numReviews: 10,
        countInStock: 20,
        slug:'iphone13ProMax',
        description: 'A popular mobile phone',
      },
      {
        name: 'Iphone 11',
        category: 'Phone',
        image: '/images/iphone13.jpg',
        price: 60000,
        brand: 'Apple',
        rating: 4.5,
        numReviews: 10,
        countInStock: 20,
        slug:'samsung',
        description: 'A popular mobile phone',
      },
      {
        name: 'Iphone 11',
        category: 'Phone',
        image: '/images/iphone13.jpg',
        price: 60000,
        brand: 'Apple',
        rating: 4.5,
        numReviews: 10,
        countInStock: 20,
        slug:'iphone11',
        description: 'A popular mobile phone',
      },
      {
        name: 'Iphone 11',
        category: 'Phone',
        image: '/images/iphone13.jpg',
        price: 60000,
        brand: 'Apple',
        rating: 4.5,
        numReviews: 10,
        countInStock: 20,
        slug:'iphone',
        description: 'A popular mobile phone',
      },
    ],
  };
  export default data;